version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1 # Use a recent stable version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic # !!! CHANGE THIS PASSWORD IN A REAL ENVIRONMENT !!!
      - xpack.security.http.ssl.enabled=false # Disable SSL for simplicity in local testing
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:elastic http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 10s
      timeout: 10s
      retries: 12

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1 # Match ES version
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy # Wait for Elasticsearch to be healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # Use the built-in kibana_system user per Elastic documentation
      - ELASTICSEARCH_USERNAME=kibana_system # Use the actual built-in user
      - ELASTICSEARCH_PASSWORD=kibanapass # Must match KIBANA_SYSTEM_PASSWORD in seed_data.py
      - SERVER_SSL_ENABLED=false
      # Set encryption keys via ENV VARS (uppercase, underscores)
      # Keys must be at least 32 characters long.
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=a_fixed_test_encryption_key_32_bytes_long
      - XPACK_REPORTING_ENCRYPTIONKEY=another_fixed_test_key_32_bytes_long_too
      - XPACK_SECURITY_ENCRYPTIONKEY=yet_another_fixed_test_key_32b_plus_more
    ports:
      - "5601:5601"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601/api/status | grep -q 'HTTP/1.1 200 OK'"]
      interval: 10s
      timeout: 10s
      retries: 12

networks:
  elastic:
    driver: bridge

volumes: # Define persistent volumes (optional but recommended for data persistence)
  esdata:
    driver: local 